[build]
  publish = "."  # Or "references-resources" if your site is inside a subfolder
  functions = "netlify/functions"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
